global:
  scrape_interval: 15s

scrape_configs:
  - job_name: tidb
    static_configs:
      - targets:
          - tidb:10080

  - job_name: pd
    metrics_path: /metrics
    static_configs:
      - targets:
          - pd1:2379
          - pd2:2379
          - pd3:2379

  - job_name: tikv
    metrics_path: /metrics
    static_configs:
      - targets:
          - tikv1:20180
          - tikv2:20180
          - tikv3:20180
