# version: '3'

# services:
#   registry:
#     image: registry:2
#     ports:
#       - "5000:5000"
#     volumes:
#       - ./registry:/var/lib/registry
#     environment:
#       REGISTRY_AUTH: htpasswd
#       REGISTRY_AUTH_HTPASSWD_PATH: /var/lib/registry/htpasswd
#       REGISTRY_AUTH_HTPASSWD_REALM: Registry

#   nginx:
#     image: nginx:latest
#     ports:
#       - "80:80"
#     volumes:
#       - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#     depends_on:
#       - registry

# version: '3'

# services:
#   portus:
#     image: dobernoeder/portus:latest
#     ports:
#       - "3000:3000"
#     environment:
#       - PORTUS_MACHINE_FQDN=127.0.0.1:3000
#       - PORTUS_DB_ADAPTER=mysql
#       - PORTUS_DB_HOST=127.0.0.1
#       - PORTUS_DB_PORT=3306
#       - PORTUS_DB_DATABASE=docker_images
#       - PORTUS_DB_USERNAME=root
#       - PORTUS_DB_PASSWORD=12345678
#       - PORTUS_SECRET_KEY_BASE=12345678
#     volumes:
#       - /Users/local/docker/images:/certs
#     depends_on:
#       - db

#   db:
#     image: mysql
#     environment:
#       MYSQL_DATABASE: docker_images
#       MYSQL_USER: root
#       MYSQL_PASSWORD: 12345678
#       MYSQL_ROOT_PASSWORD: 12345678

# version: '3'

# services:
#   registry:
#     image: registry:2
#     networks:
#       - docker_images_net
#     ports:
#       - "5000:5000"
#     volumes:
#       - ./config.yml:/etc/docker/registry/config.yml
#     restart: always

#   registry-ui:
#     image: leixinyue/docker-registry-web
#     networks:
#       - docker_images_net
#     ports:
#       - "9090:80"
#     environment:
#       - REGISTRY_URL=http://127.0.0.1:5000/v2
#       - REGISTRY_NAME=127.0.0.1:5000
#     depends_on:
#       - registry

# networks:
#   docker_images_net:
#     driver: bridge
#     ipam:
#       config:
#         - subnet: 172.30.0.0/16

version: '3.1'

services:
  harbor:
    image: easzlab/harbor-offline:v2.8.4
    hostname: 127.0.0.1:8899 # 请替换为你的域名
    networks:
      - common
    environment:
      HARBOR_ADMIN_PASSWORD: 12345678 # 请替换为你的管理员密码
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/harbor:/data

networks:
  common:
    external: true
