version: '3'

services:
  portainer:
    image: portainer/portainer
    networks:
      - common
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data

networks:
  common:
    external: true
