version: '3.5'
# 网络配置
# networks:
#   backend:
#     driver: ${NETWORKS_DRIVER}

networks:
  common:
    external: true

# 服务容器配置
services:
  wukongim:
    # wukongim底层通讯服务
    image: zyuan909/wukongim:latest
    container_name: tsdd_im
    # restart: always
    volumes:
      - ${DATA_PATH_HOST}/tsdd_im:/root/wukongim
    environment:
      WK_MODE: "debug"
      WK_EXTERNAL_IP: "13.201.220.225"
    networks:
      - common
    ports:
      - 5001:5001 # http api 端口
      - 5100:5100 # tcp端口
      - 5200:5200 # websocket端口
      - 5300:5300 # monitor端口
  tsdd:
    image: zyuan909/tsdd_server:latest
    container_name: tsdd_server
    ports:
      - "8090:8090"
      - "6979:6979"
    volumes:
      - ${DATA_PATH_HOST}/tsdd_server:/home/configs
      - ${DATA_PATH_HOST}/tsdd_server/push:/home/configs/push
    networks:
      - common
    depends_on:
      - redis
      - wukongim